"""add social_media and website to accommodation_requests

Revision ID: 15dce7787334
Revises: 25dc1d61e4f1
Create Date: 2026-03-01 11:25:32.321372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dce7787334'
down_revision = '25dc1d61e4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_media', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_requests', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('social_media')

    # ### end Alembic commands ###
