"""add accommodation_requests

Revision ID: 25dc1d61e4f1
Revises: a4c937631a72
Create Date: 2026-03-01 11:10:59.418308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25dc1d61e4f1'
down_revision = 'a4c937631a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('roommate_gender_pref', sa.String(length=20), nullable=False),
    sa.Column('smoker', sa.Boolean(), nullable=False),
    sa.Column('accepts_smoker', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodation_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodation_requests_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodation_requests_email'))

    op.drop_table('accommodation_requests')
    # ### end Alembic commands ###
